# library(shiny)
# library(rgdal)
# library(raster)
# library(dplyr)
# library(shinyFiles)
# library(shinyWidgets)
# library(shinycssloaders)
# library(parallel)
# library(doSNOW)
# library(leaflet)
# library(ggplot2)
# library(plotly)
# source("/home/lemasle_pg/Desktop/temp_LETG/modelisation_adviclim.R")
config <- config::get()
